### ISSUE TITLE
17/08/2022 9:24:06 am: Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by loveu2-alt** [qiangqiang101/BennysOriginalMotorWorks#4]
https://github.com/qiangqiang101/BennysOriginalMotorWorks/blob/e46b69e7c436f257df91d354d41213b64287a4c4/BennysOriginalMotorworks/Class/Helper.vb#L1991
[SPB.log](https://github.com/qiangqiang101/BennysOriginalMotorWorks/files/9402556/SPB.log)

**Comment by qiangqiang101** [comment]
that means Benny's ped model can't be found in your game, it has nothing to do with the script.
